# Generated by Django 5.0.1 on 2024-02-01 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estore_app', '0008_remove_order_total_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='total_price',
            field=models.IntegerField(default=1, editable=False),
            preserve_default=False,
        ),
    ]
