# Generated by Django 5.0.1 on 2024-02-01 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estore_app', '0011_alter_order_total_price'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={},
        ),
        migrations.DeleteModel(
            name='OrderItem',
        ),
    ]
