# Generated by Django 5.0.1 on 2024-02-02 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estore_app', '0012_alter_product_options_delete_orderitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='quantity',
            field=models.PositiveIntegerField(default=1, verbose_name='Количество'),
        ),
    ]
