# Generated by Django 5.0.1 on 2024-02-02 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estore_app', '0016_alter_order_total_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='total_price',
            new_name='price',
        ),
    ]
